routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['as' => 'front.'], function () {
    Route::get('/locale/set/{locale}',
        [App\Http\Controllers\Front\FrontController::class, 'setLocale'])->name('locale.set');


    Route::get('/volunteer/search/form', function () {
        return redirect(route('front.volunteer.index'));
    });
    Route::get('/join', function () {
        return redirect(route('front.organisation.add'));
    });
    Route::get('/join', function () {
        return redirect(route('front.organisation.add'));
    });

    Route::match(['get', 'post'], '/sms',
        [App\Http\Controllers\Front\FrontController::class, 'sms'])->name('front.sms');
    Route::get('/data/organisations',
        [App\Http\Controllers\Front\FrontController::class, 'dataOrganisations'])
        ->name('front.dataOrganisations');

    Route::match(['get', 'post'], '/',
        [App\Http\Controllers\Front\OrganisationController::class, 'index'])
        ->name('index');
    Route::group(['prefix' => 'organisation', 'as' => 'organisation.'], function () {
        Route::get('/search',
            [App\Http\Controllers\Front\OrganisationController::class, 'search'])
            ->name('search');
        Route::match(['get', 'post'], '/add',
            [App\Http\Controllers\Front\OrganisationController::class, 'add'])
            ->name('add');
        Route::match(['get', 'post'], '/update/{hash}',
            [App\Http\Controllers\Front\OrganisationController::class, 'update'])
            ->name('update');
        Route::get('/{item}',
            [App\Http\Controllers\Front\OrganisationController::class, 'view'])
            ->name('id');
        Route::get('/confirm/{hash}',
            [App\Http\Controllers\Front\OrganisationController::class, 'confirm'])
            ->name('confirm');
    });
    Route::group(['prefix' => 'project', 'as' => 'project.'], function () {
        Route::get('/', [App\Http\Controllers\Front\ProjectController::class, 'index'])
            ->name('index');
        Route::get('/{item}',
            [App\Http\Controllers\Front\ProjectController::class, 'view'])
            ->name('id');
    });
    Route::group(['prefix' => 'event', 'as' => 'calendarEvent.'], function () {
        Route::get('/', [App\Http\Controllers\Front\CalendarEventController::class, 'index'])
            ->name('index');
        Route::match(['get', 'post'], '/form',
            [App\Http\Controllers\Front\CalendarEventController::class, 'form'])
            ->name('form');
        Route::get('/{item}',
            [App\Http\Controllers\Front\CalendarEventController::class, 'view'])
            ->name('id');
    });
    Route::group(['prefix' => 'googleMap', 'as' => 'googleMap.'], function () {
        Route::get('/', [App\Http\Controllers\Front\GoogleMapController::class, 'index'])
            ->name('index');
    });
    Route::group(['prefix' => 'volunteer', 'as' => 'volunteer.'], function () {
        Route::get('/', [App\Http\Controllers\Front\VolunteerController::class, 'index'])
            ->name('index');
        Route::get('/search', [App\Http\Controllers\Front\VolunteerController::class, 'search'])
            ->name('search');
        Route::match(['get', 'post'], '/form/{item}',
            [App\Http\Controllers\Front\VolunteerController::class, 'form'])
            ->name('form');

        Route::match(['get', 'post'], '/feedback',
            [App\Http\Controllers\Front\VolunteerController::class, 'feedback'])
            ->name('feedback');
    });

    Route::group(['prefix' => 'render', 'as' => 'render.'], function () {
        Route::get('/stateByCountry',
            [App\Http\Controllers\Front\RenderController::class, 'stateByCountry'])
            ->name('stateByCountry');
        Route::get('/cityByState',
            [App\Http\Controllers\Front\RenderController::class, 'cityByState'])
            ->name('cityByState');
        Route::get('/phone',
            [App\Http\Controllers\Front\RenderController::class, 'renderPhone'])
            ->name('phone');
        Route::get('/email',
            [App\Http\Controllers\Front\RenderController::class, 'renderEmail'])
            ->name('email');
    });
});
Route::group(['prefix' => 'backend', 'as' => 'backend.'], function () {
    Route::group(['prefix' => 'auth', 'as' => 'auth.'], function () {
        Route::match(['get', 'post'], '/login',
            [\App\Http\Controllers\Backend\AuthController::class, 'login'])->name('login');
        Route::match(['get', 'post'], '/logout',
            [\App\Http\Controllers\Backend\AuthController::class, 'logout'])->name('logout');
    });
});

Route::group(['prefix' => 'backend', 'as' => 'backend.', 'middleware' => 'auth'], function () {
    Route::get('/',
        [App\Http\Controllers\Backend\BackendController::class, 'index'])
        ->name('index');
    Route::post('upload_image',
        [App\Http\Controllers\Backend\UploadController::class, 'uploadImage'])
        ->name('upload');
    Route::group(['middleware' => 'isAdmin'], function () {
        Route::group(['prefix' => 'organisation', 'as' => 'organisation.'], function () {
            Route::match(['get', 'post'], '/',
                [App\Http\Controllers\Backend\OrganisationController::class, 'index'])
                ->name('index');
            Route::get('/form',
                [App\Http\Controllers\Backend\OrganisationController::class, 'form'])
                ->name('form');
            Route::get('/form/{id}',
                [App\Http\Controllers\Backend\OrganisationController::class, 'form'])
                ->name('form.id');
            Route::post('/form',
                [App\Http\Controllers\Backend\OrganisationController::class, 'form']);
            Route::post('/form/{id}',
                [App\Http\Controllers\Backend\OrganisationController::class, 'form']);

            Route::get('/action/{id}',
                [App\Http\Controllers\Backend\OrganisationController::class, 'action'])
                ->name('action.id');

            Route::get('/render/phone',
                [App\Http\Controllers\Backend\OrganisationController::class, 'renderPhone'])
                ->name('render.phone');
            Route::get('/render/email',
                [App\Http\Controllers\Backend\OrganisationController::class, 'renderEmail'])
                ->name('render.email');
        });
        Route::group(['prefix' => 'project', 'as' => 'project.'], function () {
            Route::match(['get', 'post'], '/',
                [App\Http\Controllers\Backend\ProjectController::class, 'index'])
                ->name('index');
            Route::match(['get', 'post'], '/form',
                [App\Http\Controllers\Backend\ProjectController::class, 'form'])
                ->name('form');
            Route::match(['get', 'post'], '/apiImport',
                [App\Http\Controllers\Backend\ProjectController::class, 'apiImport'])
                ->name('apiImport');

            Route::match(['get', 'post'], '/form/{id}',
                [App\Http\Controllers\Backend\ProjectController::class, 'form'])
                ->name('form.id');

            Route::get('/action/{id}',
                [App\Http\Controllers\Backend\ProjectController::class, 'action'])
                ->name('action.id');
        });
        Route::group(['prefix' => 'calendarEvent', 'as' => 'calendarEvent.'], function () {
            Route::match(['get', 'post'], '/',
                [App\Http\Controllers\Backend\CalendarEventController::class, 'index'])
                ->name('index');
            Route::match(['get', 'post'], '/form',
                [App\Http\Controllers\Backend\CalendarEventController::class, 'form'])
                ->name('form');
            Route::match(['get', 'post'], '/form/{id}',
                [App\Http\Controllers\Backend\CalendarEventController::class, 'form'])
                ->name('form.id');
            Route::get('/action/{id}',
                [App\Http\Controllers\Backend\CalendarEventController::class, 'action'])
                ->name('action.id');
        });
        Route::group(['prefix' => 'programType', 'as' => 'programType.'], function () {
            Route::get('/', [App\Http\Controllers\Backend\ProgramTypeController::class, 'index'])
                ->name('index');
            Route::get('/form', [App\Http\Controllers\Backend\ProgramTypeController::class, 'form'])
                ->name('form');
            Route::get('/form/{id}',
                [App\Http\Controllers\Backend\ProgramTypeController::class, 'form'])
                ->name('form.id');
            Route::post('/form',
                [App\Http\Controllers\Backend\ProgramTypeController::class, 'form']);
            Route::post('/form/{id}',
                [App\Http\Controllers\Backend\ProgramTypeController::class, 'form']);
            Route::get('/action/{id}',
                [App\Http\Controllers\Backend\ProgramTypeController::class, 'action'])
                ->name('action.id');
        });
        Route::group(['prefix' => 'optionCategory', 'as' => 'optionCategory.'], function () {
            Route::get('/', [App\Http\Controllers\Backend\OptionCategoryController::class, 'index'])
                ->name('index');
            Route::get('/form',
                [App\Http\Controllers\Backend\OptionCategoryController::class, 'form'])
                ->name('form');
            Route::get('/form/{id}',

app/Http/Controllers/Front/CalendarEventController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\CalendarEvent;
use App\Services\CalendarEventService;
use App\Services\LocationService;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class CalendarEventController extends Controller
{
    public $baseModel = CalendarEvent::class;
    public $viewName = 'calendarEvent';

    public function index(Request $request)
    {
        $query = $this->baseModel::where(
            [
                ['status_id', CalendarEvent::STATUS_APPROVE],
                ['date_start', '<=', Date('Y-m-d H:i:s')],
                ['date_end', '>=', Date('Y-m-d H:i:s')],
            ]
        );
        $filters = $request->only([
            'center_zip',
            'country_id',
            'city_id',
            'state_id',
            'title',
            'zip',
            'address',
            'radius_quantity',
            'date_at'
        ]);
        if ($request->get('s')) {
            $filters['s'] = 1;
            $center_zip =
                preg_replace('/[^0-9]+/', '', $request->get('center_zip'));
            if ($center_zip) {

                $radius_quantity =
                    !empty($filters['radius_quantity']) ? $filters['radius_quantity'] : 3959;

                $distance = $request->get('distance', 25);
                $distance = $distance >= 5 ? $distance : 5;
                $filters['distance'] = $distance;
                $res = LocationService::getDataByAddress($center_zip);
                $lat = $res['lat'];
                $lng = $res['lng'];

                if ($lat && $lng) {
                    $query->whereHas('address', function (Builder $query) use (
                        $lat,
                        $lng,
                        $radius_quantity,
                        $center_zip,
                        $distance
                    ) {
                        $whereRaw =
                            "($radius_quantity * acos(cos(radians($lat)) * cos(radians(lat)) * cos(radians(lng) - radians($lng)) + sin(radians($lat)) * sin(radians(lat))))";
                        $query->selectRaw("{$whereRaw} AS distance")
                            ->whereRaw("{$whereRaw} < ?", [$distance])
                            ->orderByRaw('FIELD (zip, ' . $center_zip . ') DESC');
                    });
                    $query->join('addresses', 'addresses.id', '=', 'calendar_events.address_id')
                        ->orderByRaw('FIELD (addresses.zip, ' . $center_zip . ') DESC')
                        ->select('calendar_events.*');
                } else {
                    $query->where('id', -1);
                }

            } else {
                if (!empty($filters['title'])) {
                    $query->where('title', 'LIKE', '%' . $filters['title'] . '%');
                }
                if (!empty($filters['date_at'])) {
                    $query->where('title', 'LIKE', '%' . $filters['date_at'] . '%');
                }
                if (!empty($filters['country_id']) || !empty($filters['address'])
                    || !empty($filters['zip'])
                ) {
                    $query->whereHas('address', function (Builder $query) use ($filters) {
                        if (!empty($filters['country_id'])) {
                            $query->where('country_id', $filters['country_id']);
                        }
                        if (!empty($filters['state_id'])) {
                            $query->where('state_id', $filters['state_id']);
                        }
                        if (!empty($filters['city_id'])) {
                            $query->where('city_id', $filters['city_id']);
                        }
                        if (!empty($filters['address'])) {
                            $query->where('address', 'LIKE', '%' . $filters['address'] . '%');
                        }
                        $filters['zip'] = preg_replace('/[^0-9]+/', '', !empty($filters['zip'])?$filters['zip']:'');
                        if (!empty($filters['zip'])) {
                            $query->where('zip', $filters['zip']);
                        }
                    });
                }

            }
        }

        $orderField = $request->get('s_f', 'id');
        $orderBy = $request->get('s_o', 'desc');
        $orderBy = in_array($orderBy, ['asc', 'desc']) ? $orderBy : 'desc';

        $filters['s_f'] = $orderField;
        $filters['s_o'] = $orderBy;

        switch ($orderField) {
            case 'address':
                $query->join('addresses', 'addresses.id', '=', 'calendar_events.address_id')
                    ->orderBy('addresses.address', $orderBy)
                    ->select('calendar_events.*');
                break;
            default:
                $query->orderBy($orderField, $orderBy);
                break;
        }

        return view("front.$this->viewName.index",
            [
                'pagination' => $query->paginate(15, ['*'], 'page',
                    $request->get('page', 1)),
                'filters' => $filters
            ]);
    }

    public function view(Request $request, CalendarEvent $item)
    {
        return view("front.$this->viewName.view",
            [
                'item' => $item
            ]);
    }

    public function form(Request $request)
    {
        if ($request->isMethod('post')) {
            $data = $request->only([
                'country_id',
                'city_id',
                'state_id',
                'address',
                'zip',
                'title',
                'date_start',
                'date_end',
                'url',
                'type_id',
                'date_at',
                'contact',
            ]);
            $data['phones'] = [
                ['phone' => $data['contact']['phone']]
            ];
            $data['emails'] = [
                ['email' => $data['contact']['email']]
            ];
            $data['image_1920x1080'] = $request->file('image_1920x1080');
            $data['image_1080x1920'] = $request->file('image_1080x1920');
            CalendarEventService::save($data);
            $request->session()->flash('alert_message', 'Event added, await confirmation');
            return redirect(route("front.$this->viewName.index"));
        }

        return view("front.$this->viewName.form");
    }
}

app/Http/Controllers/Front/GoogleMapController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class GoogleMapController extends Controller
{

    public function index(Request $request)
    {

        if ($request->get('lat') && $request->get('lng')) {
            $keyword = $request->get('keyword');
            $lat = $request->get('lat', 39.10652688856946);
            $lng = $request->get('lng', -94.58589170968715);
            $url =
                "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location={$lat},{$lng}&radius=30000&type=bar,cafe,meal_takeaway,restaurant&keyword={$keyword}&key=AIzaSyDfkS3g2smm4new9R2s0o4p464tiRKP0ds";
            $r = json_decode(file_get_contents($url), true);
            $locations = array();

            if (!empty($r['results']) && count($r['results'])) {
                foreach ($r['results'] as $item) {
                    $locations[] = array(
                        'lat' => $item['geometry']['location']['lat'],
                        'lng' => $item['geometry']['location']['lng'],
                    );
                }
            }
            return response()->json(['locations' => $locations]);
        }
        return view('front.googleMap.index');
    }
}

resources/views/front/volunteer/index.blade.php
@extends('front.partials.layout')

@section('content')
    <div class="_container">
        @include('front.partials.subheader')
        @include('front.partials.tabs')
        @if(!\App\Services\SettingService::getValueBySlug('volunteer_is_active',true))
            <div class="inactive_page">
                {!! \App\Services\SettingService::getValueBySlug('volunteer_inactive_html','<div>Inactive</div>') !!}
            </div>
        @else
            <div class="volunteer_index">
                <div class="left-panel">
                    <div class="logo">
                        <img src="https://whyhunger.org/wp-content/uploads/2017/04/WhyHunger_WebsiteLogo-01-e1492807552348-1-e1493224274299.png">
                    </div>
                    <div class="text">
                        <b>{{__('volunteer.index.instruction_1')}}</b>
                        <br />
                        {{__('volunteer.index.instruction_2')}}
                    </div>
                    <div class="assistance">
                        <b>{{__('volunteer.index.need_assistance')}}</b>
                        <br />
                        {{__('volunteer.index.visit')}} <a
                                href="https://WhyHunger.org/FindFood">WhyHunger.org/FindFood</a>
                    </div>
                </div>
                <div class="right-panel">
                    <div class="title">{{__('volunteer.index.calling_volunteers')}}</div>
                    <div class="description">
                        {{__('volunteer.index.description')}}
                    </div>
                    <div class="admonition">
                        {{__('volunteer.index.admonition')}}
                    </div>
                    <form action="{{route('front.volunteer.search')}}">
                        <input name="zip" type="text" placeholder="{{__('volunteer.index.enter_zip')}}" />
                        @if(!Cookie::has('uhf_id'))
                            <div class="field">
                                <div class="title">{{__('organisation.form.how_did_you_find_us')}}:</div>
                                <div class="body">
                                    <div class="input">
                                        <select name="how_find" required id="how_find">
                                            @foreach(\App\Models\UserHowFindValue::all() as $v)
                                                <option value="{{$v->id}}">{{$v->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="input" id="how_find_other" style="display: none">
                                        <input type="text" placeholder="Other value" name="how_find_other">
                                    </div>
                                </div>
                            </div>
                        @endif
                        <input type="submit" value="{{__('volunteer.index.started')}}" />
                    </form>
                </div>
            </div>
        @endif
    </div>
    @php
        $value = \App\Models\UserHowFindValue::where('name','Other')->first();
    @endphp
    <input type="hidden" value="{{$value?$value->id:0}}" id="how_find_other_id" />
@endsection

resources/views/front/volunteer/search.blade.php
@extends('front.partials.layout')

@section('content')
    <div class="_container">
        @include('front.partials.subheader')
        @include('front.partials.tabs')
        <div class="volunteer_search">

            <div class="list">
                <div class="title">{{__('volunteer.search.call')}}</div>
                <div class="sub_title">{{__('volunteer.search.call_description')}}</div>
                @foreach($items as $item)
                    <div class="item">
                        <div class="left-panel">
                            <div class="title">{{ $item->title }}</div>
                            <div class="sub_title">
                                {{ $item->address->FullAddress }}
                            </div>
                        </div>
                        <div class="right-panel">
                            <a href="{{route('front.volunteer.form',['item'=>$item->id])}}">Start <img
                                        src="/img/arrow-right-white.svg" /></a>
                        </div>
                    </div>
                @endforeach
            </div>

            <div class="footer_actions">
                <button id="feedback_form_toggle">{{__('volunteer.search.feedback_form')}}</button>
                <a href="{{route('front.organisation.add')}}">{{__('volunteer.search.add_a_site')}}</a>
            </div>
            <form class="feedback_form" action="{{route('front.volunteer.feedback')}}" method="POST"
                  style="{{Cookie::get('volunteer_id') == false?'':'display:none;'}}"
            >
                <div class="title">{{__('volunteer.search.thank_for_time')}}</div>
                <div class="input_label">{{__('volunteer.search.name')}}</div>
                <div style="display: flex; justify-content: space-between">
                    <input type="text" name="first_name" placeholder="First name" style="width: 49%" required />
                    <input type="text" name="last_name" placeholder="Last name" style="width: 49%" required />
                </div>
                <div class="input_label">{{__('volunteer.search.email')}}</div>
                <div><input type="email" name="email" placeholder="Your email" required/></div>
                <div class="input_label">{{__('volunteer.search.feedback')}}</div>
                <div class="footer">
                    <textarea name="feedback"></textarea>
                    <div>
                        <button type="submit">{{__('volunteer.search.submit')}}</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
@endsection